[package]
name = "solana-zk-token-proof-program-tests"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana"
version = "1.14.22"
license = "Apache-2.0"
edition = "2021"
publish = false

[dev-dependencies]
bytemuck = { version = "1.11.0", features = ["derive"] }
solana-program-runtime = { path = "../../program-runtime", version = "=1.14.22" }
solana-program-test = { path = "../../program-test", version = "=1.14.22" }
solana-sdk = { path = "../../sdk", version = "=1.14.22" }
solana-zk-token-sdk = { path = "../../zk-token-sdk", version = "=1.14.22" }
